---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-st2-pack-configs
  annotations:
    description: Custom Coditation pack configs, shipped in '/opt/coditation/configs/'
  labels:
    app: st2
    tier: backend
    vendor: coditation
    support: {{ template "supportMethod" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ toYaml .Values.st2.packs.configs | indent 2 }}
