---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-st2-auth
  annotations:
    description: Coditation username and password, used for basic .htaccess auth
  labels:
    app: st2
    tier: backend
    vendor: coditation
    support: {{ template "supportMethod" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  # Username, used to login to Coditation system (default: st2admin)
  username: {{ required "A valid secret 'st2.username' is required for Coditation auth!" .Values.secrets.st2.username | b64enc | quote }}
  # Password, used to login to Coditation system (default: Ch@ngeMe)
  password: {{ required "A valid secret 'st2.password' is required for Coditation auth!" .Values.secrets.st2.password | b64enc | quote }}
